app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    type: rest
    resource: AppBundle\Controller\UsersController

login_check:
    path: /login_check

# REST
# api_page:
    # type:           rest
    # resource:       ApiBundle\Controller\Rest\PageController
